In [1]:
import pandas as pd
from datasets import load_dataset

In [2]:
# Login using huggingface token to access this dataset
ds = load_dataset("newfacade/LeetCodeDataset", split="train")

In [3]:
df = pd.DataFrame(ds)
df.head()
# df.to_csv("LeetCodeDataset.csv", index=False)

,task_id,question_id,difficulty,tags,problem_description,starter_code,estimated_date,prompt,completion,entry_point,test,input_output,query,response
0,two-sum,1,Easy,"[Array, Hash Table]",Given an array of integers nums and an integer...,"class Solution:\n def twoSum(self, nums: Li...",2015-08-07,import random\nimport functools\nimport collec...,"class Solution:\n def twoSum(self, nums: Li...",Solution().twoSum,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums = [3,3], target = 6', 'output...",You are an expert Python programmer. You will ...,"To solve this problem efficiently, we can use ..."
1,add-two-numbers,2,Medium,"[Recursion, Linked List, Math]",You are given two non-empty linked lists repre...,# Definition for singly-linked list.\n# class ...,2015-08-07,import heapq\nimport itertools\nfrom sortedcon...,# Definition for singly-linked list.\n# class ...,Solution().addTwoNumbers,def check(candidate):\n assert is_same_list...,"[{'input': 'l1 = [9,8,7], l2 = [1,2,3]', 'outp...",You are an expert Python programmer. You will ...,```python\n# Definition for singly-linked list...
2,longest-substring-without-repeating-characters,3,Medium,"[Hash Table, String, Sliding Window]","Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...,2015-08-07,import collections\nimport string\nimport math...,class Solution:\n def lengthOfLongestSubstr...,Solution().lengthOfLongestSubstring,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abcabcbb""', 'output': '3'}, {...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def lengthOfLo...
3,median-of-two-sorted-arrays,4,Hard,"[Array, Binary Search, Divide and Conquer]",Given two sorted arrays nums1 and nums2 of siz...,class Solution:\n def findMedianSortedArray...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def findMedianSortedArray...,Solution().findMedianSortedArrays,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums1 = [100,200,300], nums2 = [15...",You are an expert Python programmer. You will ...,```python\nfrom typing import List\n\nclass So...
4,longest-palindromic-substring,5,Medium,"[Two Pointers, String, Dynamic Programming]","Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def longestPalindrome(sel...,Solution().longestPalindrome,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abba""', 'output': 'abba'}, {'...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def longestPal...

In [ ]:
# Load complexity data and merge with main dataset
df_with_complexity = pd.read_csv("LeetCodeDataset_with_complexity.csv")

# Merge on task_id (assuming that's the common column)
df_merged = df.merge(
    df_with_complexity, on="task_id", how="left", suffixes=("", "_complexity")
)

# Save the merged dataset
df_merged.to_csv("LeetCodeQuestions.csv", index=False)
print(
    f"Merged dataset saved with {len(df_merged)} rows and {len(df_merged.columns)} columns"
)
df_merged.head()

Merged dataset saved with 2641 rows and 17 columns

,task_id,question_id,difficulty,tags,problem_description,starter_code,estimated_date,prompt,completion,entry_point,test,input_output,query,response,problem_description_complexity,optimal_time_complexity,optimal_space_complexity
0,two-sum,1,Easy,"[Array, Hash Table]",Given an array of integers nums and an integer...,"class Solution:\n def twoSum(self, nums: Li...",2015-08-07,import random\nimport functools\nimport collec...,"class Solution:\n def twoSum(self, nums: Li...",Solution().twoSum,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums = [3,3], target = 6', 'output...",You are an expert Python programmer. You will ...,"To solve this problem efficiently, we can use ...",Given an array of integers nums and an integer...,O(n),O(n)
1,add-two-numbers,2,Medium,"[Recursion, Linked List, Math]",You are given two non-empty linked lists repre...,# Definition for singly-linked list.\n# class ...,2015-08-07,import heapq\nimport itertools\nfrom sortedcon...,# Definition for singly-linked list.\n# class ...,Solution().addTwoNumbers,def check(candidate):\n assert is_same_list...,"[{'input': 'l1 = [9,8,7], l2 = [1,2,3]', 'outp...",You are an expert Python programmer. You will ...,```python\n# Definition for singly-linked list...,You are given two non-empty linked lists repre...,O(n),O(n)
2,longest-substring-without-repeating-characters,3,Medium,"[Hash Table, String, Sliding Window]","Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...,2015-08-07,import collections\nimport string\nimport math...,class Solution:\n def lengthOfLongestSubstr...,Solution().lengthOfLongestSubstring,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abcabcbb""', 'output': '3'}, {...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def lengthOfLo...,"Given a string s, find the length of the longe...",O(n),O(n)
3,median-of-two-sorted-arrays,4,Hard,"[Array, Binary Search, Divide and Conquer]",Given two sorted arrays nums1 and nums2 of siz...,class Solution:\n def findMedianSortedArray...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def findMedianSortedArray...,Solution().findMedianSortedArrays,def check(candidate):\n assert candidate(nu...,"[{'input': 'nums1 = [100,200,300], nums2 = [15...",You are an expert Python programmer. You will ...,```python\nfrom typing import List\n\nclass So...,Given two sorted arrays nums1 and nums2 of siz...,O(log n),O(1)
4,longest-palindromic-substring,5,Medium,"[Two Pointers, String, Dynamic Programming]","Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...,2015-08-07,import random\nimport functools\nimport collec...,class Solution:\n def longestPalindrome(sel...,Solution().longestPalindrome,def check(candidate):\n assert candidate(s ...,"[{'input': 's = ""abba""', 'output': 'abba'}, {'...",You are an expert Python programmer. You will ...,```python\nclass Solution:\n def longestPal...,"Given a string s, return the longest palindrom...",O(n),O(n)

:

In [8]:
df_with_questions = df[["task_id", "problem_description"]][:100]

In [7]:
df_with_questions.to_csv("LeetCodeDataset_sample_questions.csv", index=False)

In [9]:
df_with_questions_test_case = df[["task_id", "problem_description", "input_output"]][:100]

In [10]:
df_with_questions_test_case.to_csv(
    "LeetCodeDataset_sample_questions_test_cases.csv", index=False
)

In [ ]:
df_small = df.head(10)

In [ ]:
import os

test_cases_dir = "../test_cases"
os.makedirs(test_cases_dir, exist_ok=True)

unique_prompts = df["prompt"].unique()

utils_py_path = os.path.join(test_cases_dir, "utils.py")

with open(utils_py_path, "w", encoding="utf-8") as f:
    f.write("# Combined LeetCode Problem Utils\n")

    f.write(str(unique_prompts[0]))
    f.write("\n\n")

print(f"Created combined utils.py at: {os.path.abspath(utils_py_path)}")

In [ ]:
os.makedirs(test_cases_dir, exist_ok=True)

for index, row in df.iterrows():
    task_id = row["task_id"]
    test_code = row["test"]

    filename = f"{task_id}.py"
    filepath = os.path.join(test_cases_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        # Add accuracy calculation wrapper
        f.write("def calculate_accuracy(candidate):\n")
        f.write('    """\n')
        f.write(
            "    Calculate accuracy by running all test cases and counting pass/fail\n"
        )
        f.write("    Returns: (passed_count, total_count, accuracy_percentage)\n")
        f.write('    """\n')
        f.write("    passed = 0\n")
        f.write("    total = 0\n")
        f.write("    \n")

        # Parse the original test code to extract individual assertions
        lines = test_code.split("\n")
        for line in lines:
            line = line.strip()
            if line.startswith("assert candidate(") or line.startswith("assert"):
                # Extract the assertion and convert to try/except
                assertion = line[7:]  # Remove 'assert '
                f.write("    total += 1\n")
                f.write("    try:\n")
                f.write(f"        result = {assertion}\n")
                f.write("        if result:\n")
                f.write("            passed += 1\n")
                # f.write(f"        else:\n")
                # f.write(f"            print(f'Failed: {assertion}, got {{result}}')\n")
                f.write("    except Exception as e:\n")
                f.write(f"        print(f'Error in {assertion}: {{e}}')\n")
                f.write("    \n")

        f.write("    accuracy = (passed / total * 100) if total > 0 else 0\n")
        f.write("    return passed, total, accuracy\n\n")

        # Keep the original check function
        f.write(test_code)
        f.write("\n\n")

In [5]:
df_questions = (
    df[["task_id", "problem_description", "starter_code", "entry_point", "query"]]
    .drop_duplicates()
    .reset_index(drop=True)
)
df_questions.head()
df_questions.to_csv("LeetCodeQuestions.csv", index=False)

In [6]:
df_questions = pd.read_csv("LeetCodeQuestions.csv")
df_questions.head()

,task_id,problem_description,starter_code,entry_point,query
0,two-sum,Given an array of integers nums and an integer...,"class Solution:\n def twoSum(self, nums: Li...",Solution().twoSum,You are an expert Python programmer. You will ...
1,add-two-numbers,You are given two non-empty linked lists repre...,# Definition for singly-linked list.\n# class ...,Solution().addTwoNumbers,You are an expert Python programmer. You will ...
2,longest-substring-without-repeating-characters,"Given a string s, find the length of the longe...",class Solution:\n def lengthOfLongestSubstr...,Solution().lengthOfLongestSubstring,You are an expert Python programmer. You will ...
3,median-of-two-sorted-arrays,Given two sorted arrays nums1 and nums2 of siz...,class Solution:\n def findMedianSortedArray...,Solution().findMedianSortedArrays,You are an expert Python programmer. You will ...
4,longest-palindromic-substring,"Given a string s, return the longest palindrom...",class Solution:\n def longestPalindrome(sel...,Solution().longestPalindrome,You are an expert Python programmer. You will ...